version: '3.8'

services:
  bot:
    build: .
    volumes:
      - ./app:/app/app  # Монтируем папку app для live reload
      - ./.env:/app/.env  # Монтируем .env файл
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    # Для разработки можно добавить:
    # command: python -m app.main
    # или для автоперезагрузки:
    command: watchmedo auto-restart --directory=./app --pattern=*.py --recursive -- python -m app.main